"""Pure reporting helpers for Acceptance harness captures."""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from foliaseal.application.qa_evidence_contract import EvidenceContractEvaluation
from foliaseal.presentation.qt.evidence_snapshot_projection import (
    snapshot_layout_scaling as _project_layout_scaling,
)
from foliaseal.presentation.qt.evidence_snapshot_projection import (
    snapshot_layout_template as _project_layout_template,
)
from foliaseal.presentation.qt.evidence_snapshot_projection import (
    snapshot_preview_edge_distance as _project_preview_edge_distance,
)
from foliaseal.presentation.qt.evidence_snapshot_projection import (
    snapshot_request_field_count as _project_request_field_count,
)
from foliaseal.presentation.qt.evidence_snapshot_projection import (
    snapshot_reservation_margin_bottom as _project_reservation_margin_bottom,
)
from foliaseal.presentation.qt.evidence_snapshot_projection import (
    snapshot_reservation_stamp_background as _project_reservation_stamp_background,
)
from foliaseal.presentation.qt.evidence_snapshot_projection import (
    snapshot_reservation_text_length as _project_reservation_text_length,
)
from foliaseal.presentation.qt.evidence_snapshot_projection import (
    snapshot_show_field_names as _project_show_field_names,
)
from foliaseal.presentation.qt.evidence_snapshot_projection import (
    snapshot_sign_request_appearance as _project_sign_request_appearance,
)
from foliaseal.presentation.qt.evidence_snapshot_projection import (
    snapshot_stamp_position as _project_stamp_position,
)
from foliaseal.presentation.qt.evidence_snapshot_projection import (
    snapshot_visible_appearance_annotation_rect as _project_visible_annotation_rect,
)
from foliaseal.presentation.qt.evidence_snapshot_projection import (
    snapshot_visible_appearance_bbox as _project_visible_bbox,
)
from foliaseal.presentation.qt.evidence_snapshot_projection import (
    snapshot_visible_appearance_error as _project_visible_error,
)
from foliaseal.presentation.qt.evidence_snapshot_projection import (
    snapshot_visible_appearance_field_name as _project_visible_field_name,
)
from foliaseal.presentation.qt.evidence_snapshot_projection import (
    snapshot_visible_appearance_has_text as _project_visible_has_text,
)
from foliaseal.presentation.qt.evidence_snapshot_projection import (
    snapshot_visible_appearance_image_xobjects as _project_visible_xobjects,
)
from foliaseal.presentation.qt.evidence_snapshot_projection import (
    snapshot_visible_appearance_stream_length as _project_visible_stream_length,
)
from foliaseal.presentation.qt.evidence_snapshot_projection import (
    snapshot_visible_appearance_text_fragments_summary as _project_visible_fragments_summary,
)


@dataclass(frozen=True)
class InteractiveHarnessReportRequest:
    """Inputs needed to finalize one harness capture after Qt execution ends."""

    capture_payload: dict[str, Any]
    summary_json_path: str | None
    checklist_results_path: str
    checklist_template_path: str


@dataclass(frozen=True)
class InteractiveHarnessReportResult:
    """Finalized harness capture plus the rendered checklist text."""

    capture: Any
    contract: EvidenceContractEvaluation
    checklist_results: str


def build_acceptance_checklist_results_markdown(
    capture: Any,
    *,
    checklist_template_path: str,
) -> str:
    """Render a run-specific Acceptance checklist seeded from the immutable template."""

    template = Path(checklist_template_path).read_text(encoding="utf-8")
    auto_checked_items = _derive_auto_checked_items(capture)
    visible_appearance_snapshot = capture.output_visible_appearance_snapshot
    preview_content_top_distance = _snapshot_preview_edge_distance(
        capture.preview_snapshot, "content_top_to_border_px"
    )
    preview_content_bottom_distance = _snapshot_preview_edge_distance(
        capture.preview_snapshot, "content_bottom_to_border_px"
    )
    checkbox_pattern = re.compile(r"^(\s*-\s*)\[(?: |x|X)\](\s+)(.+)$")

    rendered_lines = [
        "# Acceptance FR-3B Acceptance Results",
        "",
        f"Source checklist: `{checklist_template_path}`",
        f"Captured PDF: `{capture.pdf_path}`",
        (
            f"Capture JSON path: `{capture.summary_json_path}`"
            if capture.summary_json_path
            else "Capture JSON path: not written"
        ),
        f"Results markdown path: `{capture.checklist_results_path}`",
        "",
        "This file was generated by `foliaseal interactive-harness`.",
        "Review the pre-checked items, complete the remaining manual-only checks, and keep",
        "notes in this file so acceptance can be reviewed from one artifact.",
        "",
        "## Gate status",
        "",
        f"- Acceptance tier: `{capture.acceptance_tier}`",
        f"- Automated gate verdict: `{capture.gate_verdict}`",
        f"- Evidence contract version: `{capture.evidence_contract_version}`",
        (
            f"- Evidence validation passed: {'yes' if capture.evidence_validation_passed else 'no'}"
        ),
        f"- Summary JSON written: {'yes' if capture.summary_json_written else 'no'}",
        f"- Checklist results written: {'yes' if capture.checklist_results_written else 'no'}",
        (
            "- Evidence validation errors: none"
            if not capture.evidence_validation_errors
            else f"- Evidence validation errors: {list(capture.evidence_validation_errors)}"
        ),
        (
            "- Evidence validation warnings: none"
            if not capture.evidence_validation_warnings
            else f"- Evidence validation warnings: {list(capture.evidence_validation_warnings)}"
        ),
        (
            "- Release-gating pass still requires a completed FR-3B worksheet "
            "and explicit human judgment."
        ),
        "",
        "## Automated capture summary",
        "",
        f"- First render recorded: {'yes' if capture.first_render_ms is not None else 'no'}",
        f"- Preview available: {'yes' if capture.preview_available else 'no'}",
        f"- Selection interactions captured: {capture.selection_count}",
        f"- Sign requests captured: {capture.sign_request_count}",
        f"- Request snapshot origin: {_snapshot_request_origin(capture)}",
        (
            f"- Last signature page number: {capture.last_signature_page_number}"
            if capture.last_signature_page_number is not None
            else "- Last signature page number: not captured"
        ),
        (
            "- Last sign request had visible appearance: "
            f"{'yes' if capture.last_signature_has_visible_appearance else 'no'}"
        ),
        (
            f"- Last sign request output path: `{capture.last_signature_output_path}`"
            if capture.last_signature_output_path is not None
            else "- Last sign request output path: not captured"
        ),
        (
            f"- Last request layout template: "
            f"{_snapshot_layout_template(capture.sign_request_snapshot)}"
            if capture.sign_request_snapshot is not None
            else "- Last request layout template: not captured"
        ),
        (
            f"- Last request stamp position: "
            f"{_snapshot_stamp_position(capture.sign_request_snapshot)}"
            if capture.sign_request_snapshot is not None
            else "- Last request stamp position: not captured"
        ),
        (
            f"- Last request show field names: "
            f"{'yes' if _snapshot_show_field_names(capture.sign_request_snapshot) else 'no'}"
            if capture.sign_request_snapshot is not None
            else "- Last request show field names: not captured"
        ),
        (
            f"- Last request field snapshot count: "
            f"{_snapshot_request_field_count(capture.sign_request_snapshot)}"
            if capture.sign_request_snapshot is not None
            else "- Last request field snapshot count: not captured"
        ),
        (
            f"- Backend reservation layout template: "
            f"{_snapshot_layout_template(capture.backend_reservation_snapshot)}"
            if capture.backend_reservation_snapshot is not None
            else "- Backend reservation layout template: not captured"
        ),
        (
            f"- Backend reservation stamp position: "
            f"{_snapshot_stamp_position(capture.backend_reservation_snapshot)}"
            if capture.backend_reservation_snapshot is not None
            else "- Backend reservation stamp position: not captured"
        ),
        (
            f"- Backend reservation show field names: "
            f"{'yes' if _snapshot_show_field_names(capture.backend_reservation_snapshot) else 'no'}"
            if capture.backend_reservation_snapshot is not None
            else "- Backend reservation show field names: not captured"
        ),
        (
            f"- Backend reservation field snapshot count: "
            f"{_snapshot_request_field_count(capture.backend_reservation_snapshot)}"
            if capture.backend_reservation_snapshot is not None
            else "- Backend reservation field snapshot count: not captured"
        ),
        (
            f"- Backend reservation stamp text length: "
            f"{_snapshot_reservation_text_length(capture.backend_reservation_snapshot)}"
            if capture.backend_reservation_snapshot is not None
            else "- Backend reservation stamp text length: not captured"
        ),
        (
            f"- Backend reservation stamp background: "
            f"{_snapshot_reservation_stamp_background_text(capture.backend_reservation_snapshot)}"
            if capture.backend_reservation_snapshot is not None
            else "- Backend reservation stamp background: not captured"
        ),
        (
            f"- Backend reservation background scaling: "
            f"{_snapshot_layout_scaling(capture.backend_reservation_snapshot, 'background')}"
            if capture.backend_reservation_snapshot is not None
            else "- Backend reservation background scaling: not captured"
        ),
        (
            f"- Backend reservation content scaling: "
            f"{_snapshot_layout_scaling(capture.backend_reservation_snapshot, 'content')}"
            if capture.backend_reservation_snapshot is not None
            else "- Backend reservation content scaling: not captured"
        ),
        (
            f"- Backend reservation content bottom margin: "
            f"{_snapshot_reservation_margin_bottom(capture.backend_reservation_snapshot)}"
            if capture.backend_reservation_snapshot is not None
            else "- Backend reservation content bottom margin: not captured"
        ),
        (
            f"- Preview layout template: "
            f"{_snapshot_layout_template(capture.preview_snapshot)}"
            if capture.preview_snapshot is not None
            else "- Preview layout template: not captured"
        ),
        (
            f"- Preview stamp position: "
            f"{_snapshot_stamp_position(capture.preview_snapshot)}"
            if capture.preview_snapshot is not None
            else "- Preview stamp position: not captured"
        ),
        (
            f"- Preview show field names: "
            f"{'yes' if _snapshot_show_field_names(capture.preview_snapshot) else 'no'}"
            if capture.preview_snapshot is not None
            else "- Preview show field names: not captured"
        ),
        (
            f"- Preview field snapshot count: "
            f"{_snapshot_request_field_count(capture.preview_snapshot)}"
            if capture.preview_snapshot is not None
            else "- Preview field snapshot count: not captured"
        ),
        (
            f"- Preview content top distance: {preview_content_top_distance}px"
            if preview_content_top_distance is not None
            else "- Preview content top distance: not captured"
        ),
        (
            f"- Preview content bottom distance: {preview_content_bottom_distance}px"
            if preview_content_bottom_distance is not None
            else "- Preview content bottom distance: not captured"
        ),
        f"- Validation text: {capture.validation_text or 'not captured'}",
        (
            f"- Last signing result success: "
            f"{'yes' if capture.last_signing_result_success else 'no'}"
            if capture.last_signing_result_success is not None
            else "- Last signing result success: not captured"
        ),
        (
            f"- Last signing result message: {capture.last_signing_result_message}"
            if capture.last_signing_result_message
            else "- Last signing result message: not captured"
        ),
        (
            f"- Captured error count: {len(capture.errors)}"
            if capture.errors
            else "- Captured error count: 0"
        ),
        "",
        "## Signed output summary",
        "",
        f"- Output file exists: {'yes' if capture.output_file_exists else 'no'}",
        (
            f"- Output file size: {capture.output_file_size_bytes} bytes"
            if capture.output_file_size_bytes is not None
            else "- Output file size: not captured"
        ),
        (
            f"- Output embedded signature count: {capture.output_signature_count}"
            if capture.output_signature_count is not None
            else "- Output embedded signature count: not captured"
        ),
        (
            "- Output signature field name: "
            f"{_snapshot_output_signature_value(capture.output_signature_snapshot, 'field_name')}"
            if capture.output_signature_snapshot is not None
            else "- Output signature field name: not captured"
        ),
        (
            "- Output signature name: "
            f"{_snapshot_output_signature_value(capture.output_signature_snapshot, 'name')}"
            if capture.output_signature_snapshot is not None
            else "- Output signature name: not captured"
        ),
        (
            "- Output signature location: "
            f"{_snapshot_output_signature_value(capture.output_signature_snapshot, 'location')}"
            if capture.output_signature_snapshot is not None
            else "- Output signature location: not captured"
        ),
        (
            "- Output signature contact info: "
            f"{_snapshot_output_signature_value(capture.output_signature_snapshot, 'contact_info')}"
            if capture.output_signature_snapshot is not None
            else "- Output signature contact info: not captured"
        ),
        (
            "- Output signature byte range: "
            f"{_snapshot_output_signature_value(capture.output_signature_snapshot, 'byte_range')}"
            if capture.output_signature_snapshot is not None
            else "- Output signature byte range: not captured"
        ),
        (
            "- Output signature subfilter: "
            f"{_snapshot_output_signature_value(capture.output_signature_snapshot, 'subfilter')}"
            if capture.output_signature_snapshot is not None
            else "- Output signature subfilter: not captured"
        ),
        (
            "- Output signature md algorithm: "
            f"{_snapshot_output_signature_value(capture.output_signature_snapshot, 'md_algorithm')}"
            if capture.output_signature_snapshot is not None
            else "- Output signature md algorithm: not captured"
        ),
        (
            f"- Output visible appearance field name: "
            f"{_snapshot_visible_appearance_field_name(visible_appearance_snapshot)}"
        ),
        (
            f"- Output visible appearance annotation rect: "
            f"{_snapshot_visible_appearance_annotation_rect(visible_appearance_snapshot)}"
        ),
        (
            f"- Output visible appearance bbox: "
            f"{_snapshot_visible_appearance_bbox(visible_appearance_snapshot)}"
        ),
        (
            f"- Output visible appearance stream length: "
            f"{_snapshot_visible_appearance_stream_length(visible_appearance_snapshot)} bytes"
        ),
        (
            f"- Output visible appearance has visible text: "
            f"{_snapshot_visible_appearance_has_text(visible_appearance_snapshot)}"
        ),
        (
            f"- Output visible appearance text fragments: "
            f"{_snapshot_visible_appearance_text_fragments_summary(visible_appearance_snapshot)}"
        ),
        (
            f"- Output visible appearance image XObjects: "
            f"{_snapshot_visible_appearance_image_xobjects(visible_appearance_snapshot)}"
        ),
        (
            f"- Output visible appearance error: "
            f"{_snapshot_visible_appearance_error(visible_appearance_snapshot)}"
        ),
        "",
    ]
    for raw_line in template.splitlines():
        match = checkbox_pattern.match(raw_line)
        if not match:
            rendered_lines.append(raw_line)
            continue
        prefix, spacing, item_text = match.groups()
        marker = "x" if item_text.strip() in auto_checked_items else " "
        rendered_lines.append(f"{prefix}[{marker}]{spacing}{item_text}")
    return "\n".join(rendered_lines) + "\n"


def finalize_interactive_harness_report(
    request: InteractiveHarnessReportRequest,
    *,
    contract_evaluator,
    capture_factory,
    checklist_renderer,
    text_writer,
) -> InteractiveHarnessReportResult:
    """Finalize the saved evidence payload for one interactive harness run."""

    payload = dict(request.capture_payload)
    contract = contract_evaluator(payload)
    capture = capture_factory(
        capture_payload=payload,
        contract=contract,
        summary_json_path=request.summary_json_path,
        checklist_results_path=request.checklist_results_path,
        checklist_results_written=bool(request.checklist_results_path),
    )
    text_writer(target_path=request.summary_json_path, content=capture.to_json() + "\n")
    checklist_results = checklist_renderer(
        capture,
        checklist_template_path=request.checklist_template_path,
    )
    text_writer(target_path=request.checklist_results_path, content=checklist_results)
    return InteractiveHarnessReportResult(
        capture=capture,
        contract=contract,
        checklist_results=checklist_results,
    )


def _derive_auto_checked_items(capture: Any) -> set[str]:
    auto_checked: set[str] = set()

    if capture.preview_available:
        auto_checked.add(
            "Confirm the signature properties flow is reachable from the main signing UI."
        )
        auto_checked.add(
            "Confirm the viewer preview renders before any signing action is attempted."
        )
        auto_checked.add(
            "The focused properties panel shows the available appearance controls."
        )

    if not capture.errors:
        auto_checked.add(
            "Confirm the selected PDF can be used without unexpected dependency or backend errors."
        )

    if capture.selection_count > 0:
        auto_checked.add("The user can draw a signature rectangle on the preview.")

    if capture.sign_request_count > 0:
        auto_checked.add("The sign action is available from the properties flow.")

    return auto_checked


def _snapshot_sign_request_appearance(snapshot: dict[str, Any] | None) -> dict[str, Any] | None:
    projected = _project_sign_request_appearance(snapshot)
    return None if projected is None else dict(projected)


def _snapshot_request_origin(capture: Any) -> str:
    if capture.sign_request_snapshot is None:
        return "not captured"
    if capture.sign_request_count > 0:
        return "submitted request"
    return "current draft"


def _snapshot_layout_template(snapshot: dict[str, Any] | None) -> str | None:
    return _project_layout_template(snapshot)


def _snapshot_stamp_position(snapshot: dict[str, Any] | None) -> str | None:
    return _project_stamp_position(snapshot)


def _snapshot_show_field_names(snapshot: dict[str, Any] | None) -> bool:
    return _project_show_field_names(snapshot)


def _snapshot_request_field_count(snapshot: dict[str, Any] | None) -> int:
    return _project_request_field_count(snapshot)


def _snapshot_preview_edge_distance(snapshot: dict[str, Any] | None, key: str) -> int | None:
    value = _project_preview_edge_distance(snapshot, key)
    return None if value is None else int(value)


def _snapshot_reservation_text_length(snapshot: dict[str, Any] | None) -> int:
    return _project_reservation_text_length(snapshot)


def _snapshot_reservation_stamp_background(snapshot: dict[str, Any] | None) -> bool:
    return _project_reservation_stamp_background(snapshot)


def _snapshot_reservation_stamp_background_text(snapshot: dict[str, Any] | None) -> str:
    return "yes" if _snapshot_reservation_stamp_background(snapshot) else "no"


def _snapshot_layout_scaling(snapshot: dict[str, Any] | None, key: str) -> str | None:
    return _project_layout_scaling(snapshot, key)


def _snapshot_reservation_margin_bottom(snapshot: dict[str, Any] | None) -> int | None:
    value = _project_reservation_margin_bottom(snapshot)
    return None if value is None else int(value)


def _snapshot_visible_appearance_field_name(snapshot: dict[str, Any] | None) -> str:
    return _project_visible_field_name(snapshot)


def _snapshot_output_signature_value(snapshot: dict[str, Any] | None, key: str) -> str:
    if snapshot is None:
        return "not captured"
    value = snapshot.get(key, "not captured")
    return str(value)


def _snapshot_visible_appearance_annotation_rect(snapshot: dict[str, Any] | None) -> str:
    return _project_visible_annotation_rect(snapshot)


def _snapshot_visible_appearance_bbox(snapshot: dict[str, Any] | None) -> str:
    return _project_visible_bbox(snapshot)


def _snapshot_visible_appearance_stream_length(snapshot: dict[str, Any] | None) -> int:
    return _project_visible_stream_length(snapshot)


def _snapshot_visible_appearance_has_text(snapshot: dict[str, Any] | None) -> str:
    return _project_visible_has_text(snapshot)


def _snapshot_visible_appearance_text_fragments_summary(snapshot: dict[str, Any] | None) -> str:
    return _project_visible_fragments_summary(snapshot)


def _snapshot_visible_appearance_image_xobjects(snapshot: dict[str, Any] | None) -> str:
    return _project_visible_xobjects(snapshot)


def _snapshot_visible_appearance_error(snapshot: dict[str, Any] | None) -> str:
    return _project_visible_error(snapshot)
