"""Interactive Qt harness for Phase 3 signing-shell acceptance."""

from __future__ import annotations

import importlib
import json
import re
from collections import Counter
from dataclasses import asdict, dataclass
from pathlib import Path
from time import perf_counter
from typing import Any

from foliaseal.application import SigningDraftWorkflow
from foliaseal.application.viewer_session import ViewerSession
from foliaseal.application.viewer_workflow import ViewerWorkflow
from foliaseal.domain.models import SigningRequest
from foliaseal.infra.render.qt_backend import QtPdfRenderBackend
from foliaseal.presentation.qt.signing_shell import build_qt_signing_shell

DEFAULT_PHASE3_CHECKLIST_TEMPLATE_PATH = "artifacts/phase3_fr3b_acceptance_checklist.md"
DEFAULT_PHASE3_CHECKLIST_RESULTS_PATH = "artifacts/phase3_fr3b_acceptance_results.md"


@dataclass(frozen=True)
class Phase3HarnessCapture:
    """Structured capture emitted by the interactive Phase 3 harness."""

    pdf_path: str
    first_render_ms: float | None
    selection_count: int
    sign_request_count: int
    last_signature_page_index: int | None
    last_signature_page_number: int | None
    last_signature_has_visible_appearance: bool
    last_signature_output_path: str | None
    preview_available: bool
    validation_text: str
    interaction_counts: dict[str, int]
    errors: tuple[str, ...]

    def to_json(self) -> str:
        """Return a stable JSON representation for later review."""

        return json.dumps(asdict(self), indent=2, sort_keys=True)


def build_phase3_checklist_results_markdown(
    capture: Phase3HarnessCapture,
    *,
    checklist_template_path: str = DEFAULT_PHASE3_CHECKLIST_TEMPLATE_PATH,
) -> str:
    """Render a run-specific Phase 3 checklist seeded from the immutable template."""

    template = Path(checklist_template_path).read_text(encoding="utf-8")
    auto_checked_items = _derive_phase3_auto_checked_items(capture)
    checkbox_pattern = re.compile(r"^(\s*-\s*)\[(?: |x|X)\](\s+)(.+)$")

    rendered_lines = [
        "# Phase 3 FR-3B Acceptance Results",
        "",
        f"Source checklist: `{checklist_template_path}`",
        f"Captured PDF: `{capture.pdf_path}`",
        "",
        "This file was generated by `foliaseal phase3-signing-harness`.",
        "Review the pre-checked items, complete the remaining manual-only checks, and keep",
        "notes in this file so Phase 3 acceptance can be reviewed from one artifact.",
        "",
        "## Automated capture summary",
        "",
        f"- First render recorded: {'yes' if capture.first_render_ms is not None else 'no'}",
        f"- Preview available: {'yes' if capture.preview_available else 'no'}",
        f"- Selection interactions captured: {capture.selection_count}",
        f"- Sign requests captured: {capture.sign_request_count}",
        (
            f"- Last signature page number: {capture.last_signature_page_number}"
            if capture.last_signature_page_number is not None
            else "- Last signature page number: not captured"
        ),
        (
            "- Last sign request had visible appearance: "
            f"{'yes' if capture.last_signature_has_visible_appearance else 'no'}"
        ),
        (
            f"- Last sign request output path: `{capture.last_signature_output_path}`"
            if capture.last_signature_output_path is not None
            else "- Last sign request output path: not captured"
        ),
        f"- Current validation text: `{capture.validation_text or 'n/a'}`",
        "",
    ]
    for raw_line in template.splitlines():
        match = checkbox_pattern.match(raw_line)
        if not match:
            rendered_lines.append(raw_line)
            continue
        prefix, spacing, item_text = match.groups()
        marker = "x" if item_text.strip() in auto_checked_items else " "
        rendered_lines.append(f"{prefix}[{marker}]{spacing}{item_text}")
    return "\n".join(rendered_lines) + "\n"


def run_phase3_signing_harness(
    *,
    pdf_path: str,
    summary_json_path: str | None = None,
    checklist_results_path: str = DEFAULT_PHASE3_CHECKLIST_RESULTS_PATH,
    checklist_template_path: str = DEFAULT_PHASE3_CHECKLIST_TEMPLATE_PATH,
) -> Phase3HarnessCapture:
    """Launch an interactive Qt signing-shell harness for Phase 3 acceptance."""

    bindings = _load_qt_harness_bindings()
    source_path = Path(pdf_path)
    if not source_path.exists():
        raise FileNotFoundError(f"PDF does not exist: {pdf_path}")

    page_count = _load_page_count(bindings=bindings, pdf_path=str(source_path))
    backend = QtPdfRenderBackend()
    diagnostic = backend.diagnostics()
    if not diagnostic.available:
        raise RuntimeError(diagnostic.message)

    viewer_workflow = ViewerWorkflow(
        document_path=str(source_path),
        render_backend=backend,
        session=ViewerSession(page_count=page_count),
    )
    signing_workflow = SigningDraftWorkflow(
        input_pdf_path=str(source_path),
        output_pdf_path=str(source_path.with_name(source_path.stem + "-signed.pdf")),
        certificate_path="demo-cert.p12",
        passphrase="demo-passphrase",
        tsa_url="https://tsa.example.invalid",
        timestamp_required=True,
    )

    sign_requests: list[SigningRequest] = []
    errors: list[str] = []
    interaction_counts: Counter[str] = Counter()

    app = bindings.q_application.instance() or bindings.q_application([])
    window = bindings.q_main_window()
    window.setWindowTitle(f"FoliaSeal Phase 3 Harness - {source_path.name}")
    window.resize(1440, 980)

    central = bindings.q_widget()
    layout = bindings.q_v_box_layout(central)
    toolbar = bindings.q_h_box_layout()
    layout.addLayout(toolbar)
    body_layout = bindings.q_h_box_layout()
    layout.addLayout(body_layout, 1)

    window.setCentralWidget(central)

    def refocus_shell() -> None:
        focus_setter = getattr(shell, "setFocus", None)
        if callable(focus_setter):
            focus_setter()

    def on_sign_request(request: SigningRequest) -> None:
        sign_requests.append(request)

    def on_error(message: str) -> None:
        errors.append(message)

    def on_status_change(name: str) -> None:
        interaction_counts[name] += 1

    shell = build_qt_signing_shell(
        viewer_workflow=viewer_workflow,
        signing_workflow=signing_workflow,
        on_sign_request=on_sign_request,
        on_error=on_error,
        on_status_change=on_status_change,
    )
    body_layout.addWidget(shell, 1)

    def do_refresh() -> None:
        shell.refresh_viewer()
        refocus_shell()

    def navigate(action_name: str) -> None:
        action = getattr(shell.viewer_widget, action_name)
        action()
        refocus_shell()

    controls = [
        ("Refresh", do_refresh),
        ("Prev Page", lambda: navigate("go_to_previous_page")),
        ("Next Page", lambda: navigate("go_to_next_page")),
        ("Reset Zoom", lambda: navigate("reset_zoom_view")),
        ("Confirm/Sign", shell.submit_sign_request),
    ]
    for label, callback in controls:
        button = bindings.q_push_button(label)
        button.clicked.connect(callback)
        toolbar.addWidget(button)

    toolbar.addStretch(1)

    start = perf_counter()
    shell.refresh_viewer()
    _elapsed_ms = (perf_counter() - start) * 1000.0

    window.show()
    refocus_shell()
    app.exec()

    preview_text = shell.properties_panel.preview_text()
    validation_text = shell.properties_panel.validation_text()
    last_signature_page_index = (
        sign_requests[-1].signature_rect.page_index
        if sign_requests and sign_requests[-1].signature_rect is not None
        else None
    )
    capture = Phase3HarnessCapture(
        pdf_path=str(source_path),
        first_render_ms=viewer_workflow.timing_tracker.snapshot().first_render_ms,
        selection_count=interaction_counts.get("selection_success", 0),
        sign_request_count=len(sign_requests),
        last_signature_page_index=last_signature_page_index,
        last_signature_page_number=(
            last_signature_page_index + 1 if last_signature_page_index is not None else None
        ),
        last_signature_has_visible_appearance=(
            sign_requests[-1].has_visible_signature_settings() if sign_requests else False
        ),
        last_signature_output_path=(
            sign_requests[-1].output_pdf_path if sign_requests else None
        ),
        preview_available=bool(preview_text.strip()),
        validation_text=validation_text,
        interaction_counts=dict(sorted(interaction_counts.items())),
        errors=tuple(errors),
    )
    _write_optional_text(target_path=summary_json_path, content=capture.to_json() + "\n")
    checklist_results = build_phase3_checklist_results_markdown(
        capture,
        checklist_template_path=checklist_template_path,
    )
    _write_optional_text(target_path=checklist_results_path, content=checklist_results)
    print("Phase 3 harness capture")
    print(capture.to_json())
    print()
    print(f"Checklist results file: {checklist_results_path}")
    print("Review the pre-checked items, complete the remaining manual-only checks, and")
    print("use the generated file as the acceptance worksheet for Phase 3.")
    return capture


@dataclass(frozen=True)
class _QtHarnessBindings:
    q_application: type[Any]
    q_main_window: type[Any]
    q_widget: type[Any]
    q_v_box_layout: type[Any]
    q_h_box_layout: type[Any]
    q_group_box: type[Any]
    q_push_button: type[Any]
    q_label: type[Any]
    q_plain_text_edit: type[Any]
    qpdf_document: type[Any]


def _load_qt_harness_bindings() -> _QtHarnessBindings:
    widgets = importlib.import_module("PySide6.QtWidgets")
    qtpdf = importlib.import_module("PySide6.QtPdf")
    return _QtHarnessBindings(
        q_application=getattr(widgets, "QApplication"),
        q_main_window=getattr(widgets, "QMainWindow"),
        q_widget=getattr(widgets, "QWidget"),
        q_v_box_layout=getattr(widgets, "QVBoxLayout"),
        q_h_box_layout=getattr(widgets, "QHBoxLayout"),
        q_group_box=getattr(widgets, "QGroupBox"),
        q_push_button=getattr(widgets, "QPushButton"),
        q_label=getattr(widgets, "QLabel"),
        q_plain_text_edit=getattr(widgets, "QPlainTextEdit"),
        qpdf_document=getattr(qtpdf, "QPdfDocument"),
    )


def _load_page_count(*, bindings: _QtHarnessBindings, pdf_path: str) -> int:
    document = bindings.qpdf_document()
    status = document.load(pdf_path)
    if status != bindings.qpdf_document.Error.None_:
        raise RuntimeError(f"Failed to load PDF document: {pdf_path}")
    return int(document.pageCount())


def _derive_phase3_auto_checked_items(capture: Phase3HarnessCapture) -> set[str]:
    auto_checked: set[str] = set()

    if capture.preview_available:
        auto_checked.add(
            "Confirm the signature properties flow is reachable from the main signing UI."
        )
        auto_checked.add(
            "Confirm the viewer preview renders before any signing action is attempted."
        )
        auto_checked.add(
            "The focused properties panel shows the available appearance controls."
        )

    if not capture.errors:
        auto_checked.add(
            "Confirm the selected PDF can be used without unexpected dependency or backend errors."
        )

    if capture.first_render_ms is not None:
        auto_checked.add(
            "Launch the Phase 3 desktop build in an environment with the relevant "
            "PDF signing UI enabled."
        )

    if capture.selection_count > 0:
        auto_checked.add("The user can draw a signature rectangle on the preview.")
        auto_checked.add("The resulting placement lands on the expected page area.")

    if capture.selection_count > 1:
        auto_checked.add("The placed rectangle can be resized or repositioned in the workflow.")

    if capture.sign_request_count > 0:
        auto_checked.add("The sign action is available from the properties flow.")
        auto_checked.add(
            "The app shows the expected confirmation or summary before signing, if applicable."
        )

    if capture.last_signature_page_index is not None:
        auto_checked.add("The user can choose the target page before placement.")

    return auto_checked


def _write_optional_text(*, target_path: str | None, content: str) -> None:
    if target_path is None:
        return
    path = Path(target_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
