"""Pure reporting helpers for Phase 3 harness captures."""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from foliaseal.application.qa_evidence_contract import EvidenceContractEvaluation


@dataclass(frozen=True)
class Phase3HarnessReportRequest:
    """Inputs needed to finalize one harness capture after Qt execution ends."""

    capture_payload: dict[str, Any]
    summary_json_path: str | None
    checklist_results_path: str
    checklist_template_path: str


@dataclass(frozen=True)
class Phase3HarnessReportResult:
    """Finalized harness capture plus the rendered checklist text."""

    capture: Any
    contract: EvidenceContractEvaluation
    checklist_results: str


def build_phase3_checklist_results_markdown(
    capture: Any,
    *,
    checklist_template_path: str,
) -> str:
    """Render a run-specific Phase 3 checklist seeded from the immutable template."""

    template = Path(checklist_template_path).read_text(encoding="utf-8")
    auto_checked_items = _derive_phase3_auto_checked_items(capture)
    visible_appearance_snapshot = capture.output_visible_appearance_snapshot
    preview_content_top_distance = _snapshot_preview_edge_distance(
        capture.preview_snapshot, "content_top_to_border_px"
    )
    preview_content_bottom_distance = _snapshot_preview_edge_distance(
        capture.preview_snapshot, "content_bottom_to_border_px"
    )
    checkbox_pattern = re.compile(r"^(\s*-\s*)\[(?: |x|X)\](\s+)(.+)$")

    rendered_lines = [
        "# Phase 3 FR-3B Acceptance Results",
        "",
        f"Source checklist: `{checklist_template_path}`",
        f"Captured PDF: `{capture.pdf_path}`",
        (
            f"Capture JSON path: `{capture.summary_json_path}`"
            if capture.summary_json_path
            else "Capture JSON path: not written"
        ),
        f"Results markdown path: `{capture.checklist_results_path}`",
        "",
        "This file was generated by `foliaseal phase3-signing-harness`.",
        "Review the pre-checked items, complete the remaining manual-only checks, and keep",
        "notes in this file so Phase 3 acceptance can be reviewed from one artifact.",
        "",
        "## Gate status",
        "",
        f"- Acceptance tier: `{capture.acceptance_tier}`",
        f"- Automated gate verdict: `{capture.gate_verdict}`",
        f"- Evidence contract version: `{capture.evidence_contract_version}`",
        (
            f"- Evidence validation passed: {'yes' if capture.evidence_validation_passed else 'no'}"
        ),
        f"- Summary JSON written: {'yes' if capture.summary_json_written else 'no'}",
        f"- Checklist results written: {'yes' if capture.checklist_results_written else 'no'}",
        (
            "- Evidence validation errors: none"
            if not capture.evidence_validation_errors
            else f"- Evidence validation errors: {list(capture.evidence_validation_errors)}"
        ),
        (
            "- Evidence validation warnings: none"
            if not capture.evidence_validation_warnings
            else f"- Evidence validation warnings: {list(capture.evidence_validation_warnings)}"
        ),
        (
            "- Release-gating pass still requires a completed FR-3B worksheet "
            "and explicit human judgment."
        ),
        "",
        "## Automated capture summary",
        "",
        f"- First render recorded: {'yes' if capture.first_render_ms is not None else 'no'}",
        f"- Preview available: {'yes' if capture.preview_available else 'no'}",
        f"- Selection interactions captured: {capture.selection_count}",
        f"- Sign requests captured: {capture.sign_request_count}",
        f"- Request snapshot origin: {_snapshot_request_origin(capture)}",
        (
            f"- Last signature page number: {capture.last_signature_page_number}"
            if capture.last_signature_page_number is not None
            else "- Last signature page number: not captured"
        ),
        (
            "- Last sign request had visible appearance: "
            f"{'yes' if capture.last_signature_has_visible_appearance else 'no'}"
        ),
        (
            f"- Last sign request output path: `{capture.last_signature_output_path}`"
            if capture.last_signature_output_path is not None
            else "- Last sign request output path: not captured"
        ),
        (
            f"- Last request layout template: "
            f"{_snapshot_layout_template(capture.sign_request_snapshot)}"
            if capture.sign_request_snapshot is not None
            else "- Last request layout template: not captured"
        ),
        (
            f"- Last request stamp position: "
            f"{_snapshot_stamp_position(capture.sign_request_snapshot)}"
            if capture.sign_request_snapshot is not None
            else "- Last request stamp position: not captured"
        ),
        (
            f"- Last request show field names: "
            f"{'yes' if _snapshot_show_field_names(capture.sign_request_snapshot) else 'no'}"
            if capture.sign_request_snapshot is not None
            else "- Last request show field names: not captured"
        ),
        (
            f"- Last request field snapshot count: "
            f"{_snapshot_request_field_count(capture.sign_request_snapshot)}"
            if capture.sign_request_snapshot is not None
            else "- Last request field snapshot count: not captured"
        ),
        (
            f"- Backend reservation layout template: "
            f"{_snapshot_layout_template(capture.backend_reservation_snapshot)}"
            if capture.backend_reservation_snapshot is not None
            else "- Backend reservation layout template: not captured"
        ),
        (
            f"- Backend reservation stamp position: "
            f"{_snapshot_stamp_position(capture.backend_reservation_snapshot)}"
            if capture.backend_reservation_snapshot is not None
            else "- Backend reservation stamp position: not captured"
        ),
        (
            f"- Backend reservation show field names: "
            f"{'yes' if _snapshot_show_field_names(capture.backend_reservation_snapshot) else 'no'}"
            if capture.backend_reservation_snapshot is not None
            else "- Backend reservation show field names: not captured"
        ),
        (
            f"- Backend reservation field snapshot count: "
            f"{_snapshot_request_field_count(capture.backend_reservation_snapshot)}"
            if capture.backend_reservation_snapshot is not None
            else "- Backend reservation field snapshot count: not captured"
        ),
        (
            f"- Backend reservation stamp text length: "
            f"{_snapshot_reservation_text_length(capture.backend_reservation_snapshot)}"
            if capture.backend_reservation_snapshot is not None
            else "- Backend reservation stamp text length: not captured"
        ),
        (
            f"- Backend reservation stamp background: "
            f"{_snapshot_reservation_stamp_background_text(capture.backend_reservation_snapshot)}"
            if capture.backend_reservation_snapshot is not None
            else "- Backend reservation stamp background: not captured"
        ),
        (
            f"- Backend reservation background scaling: "
            f"{_snapshot_layout_scaling(capture.backend_reservation_snapshot, 'background')}"
            if capture.backend_reservation_snapshot is not None
            else "- Backend reservation background scaling: not captured"
        ),
        (
            f"- Backend reservation content scaling: "
            f"{_snapshot_layout_scaling(capture.backend_reservation_snapshot, 'content')}"
            if capture.backend_reservation_snapshot is not None
            else "- Backend reservation content scaling: not captured"
        ),
        (
            f"- Backend reservation content bottom margin: "
            f"{_snapshot_reservation_margin_bottom(capture.backend_reservation_snapshot)}"
            if capture.backend_reservation_snapshot is not None
            else "- Backend reservation content bottom margin: not captured"
        ),
        (
            f"- Preview layout template: "
            f"{_snapshot_layout_template(capture.preview_snapshot)}"
            if capture.preview_snapshot is not None
            else "- Preview layout template: not captured"
        ),
        (
            f"- Preview stamp position: "
            f"{_snapshot_stamp_position(capture.preview_snapshot)}"
            if capture.preview_snapshot is not None
            else "- Preview stamp position: not captured"
        ),
        (
            f"- Preview show field names: "
            f"{'yes' if _snapshot_show_field_names(capture.preview_snapshot) else 'no'}"
            if capture.preview_snapshot is not None
            else "- Preview show field names: not captured"
        ),
        (
            f"- Preview field snapshot count: "
            f"{_snapshot_request_field_count(capture.preview_snapshot)}"
            if capture.preview_snapshot is not None
            else "- Preview field snapshot count: not captured"
        ),
        (
            f"- Preview content top distance: {preview_content_top_distance}px"
            if preview_content_top_distance is not None
            else "- Preview content top distance: not captured"
        ),
        (
            f"- Preview content bottom distance: {preview_content_bottom_distance}px"
            if preview_content_bottom_distance is not None
            else "- Preview content bottom distance: not captured"
        ),
        f"- Validation text: {capture.validation_text or 'not captured'}",
        (
            f"- Last signing result success: "
            f"{'yes' if capture.last_signing_result_success else 'no'}"
            if capture.last_signing_result_success is not None
            else "- Last signing result success: not captured"
        ),
        (
            f"- Last signing result message: {capture.last_signing_result_message}"
            if capture.last_signing_result_message
            else "- Last signing result message: not captured"
        ),
        (
            f"- Captured error count: {len(capture.errors)}"
            if capture.errors
            else "- Captured error count: 0"
        ),
        "",
        "## Signed output summary",
        "",
        f"- Output file exists: {'yes' if capture.output_file_exists else 'no'}",
        (
            f"- Output file size: {capture.output_file_size_bytes} bytes"
            if capture.output_file_size_bytes is not None
            else "- Output file size: not captured"
        ),
        (
            f"- Output embedded signature count: {capture.output_signature_count}"
            if capture.output_signature_count is not None
            else "- Output embedded signature count: not captured"
        ),
        (
            "- Output signature field name: "
            f"{_snapshot_output_signature_value(capture.output_signature_snapshot, 'field_name')}"
            if capture.output_signature_snapshot is not None
            else "- Output signature field name: not captured"
        ),
        (
            "- Output signature name: "
            f"{_snapshot_output_signature_value(capture.output_signature_snapshot, 'name')}"
            if capture.output_signature_snapshot is not None
            else "- Output signature name: not captured"
        ),
        (
            "- Output signature location: "
            f"{_snapshot_output_signature_value(capture.output_signature_snapshot, 'location')}"
            if capture.output_signature_snapshot is not None
            else "- Output signature location: not captured"
        ),
        (
            "- Output signature contact info: "
            f"{_snapshot_output_signature_value(capture.output_signature_snapshot, 'contact_info')}"
            if capture.output_signature_snapshot is not None
            else "- Output signature contact info: not captured"
        ),
        (
            "- Output signature byte range: "
            f"{_snapshot_output_signature_value(capture.output_signature_snapshot, 'byte_range')}"
            if capture.output_signature_snapshot is not None
            else "- Output signature byte range: not captured"
        ),
        (
            "- Output signature subfilter: "
            f"{_snapshot_output_signature_value(capture.output_signature_snapshot, 'subfilter')}"
            if capture.output_signature_snapshot is not None
            else "- Output signature subfilter: not captured"
        ),
        (
            "- Output signature md algorithm: "
            f"{_snapshot_output_signature_value(capture.output_signature_snapshot, 'md_algorithm')}"
            if capture.output_signature_snapshot is not None
            else "- Output signature md algorithm: not captured"
        ),
        (
            f"- Output visible appearance field name: "
            f"{_snapshot_visible_appearance_field_name(visible_appearance_snapshot)}"
        ),
        (
            f"- Output visible appearance annotation rect: "
            f"{_snapshot_visible_appearance_annotation_rect(visible_appearance_snapshot)}"
        ),
        (
            f"- Output visible appearance bbox: "
            f"{_snapshot_visible_appearance_bbox(visible_appearance_snapshot)}"
        ),
        (
            f"- Output visible appearance stream length: "
            f"{_snapshot_visible_appearance_stream_length(visible_appearance_snapshot)} bytes"
        ),
        (
            f"- Output visible appearance has visible text: "
            f"{_snapshot_visible_appearance_has_text(visible_appearance_snapshot)}"
        ),
        (
            f"- Output visible appearance text fragments: "
            f"{_snapshot_visible_appearance_text_fragments_summary(visible_appearance_snapshot)}"
        ),
        (
            f"- Output visible appearance image XObjects: "
            f"{_snapshot_visible_appearance_image_xobjects(visible_appearance_snapshot)}"
        ),
        (
            f"- Output visible appearance error: "
            f"{_snapshot_visible_appearance_error(visible_appearance_snapshot)}"
        ),
        "",
    ]
    for raw_line in template.splitlines():
        match = checkbox_pattern.match(raw_line)
        if not match:
            rendered_lines.append(raw_line)
            continue
        prefix, spacing, item_text = match.groups()
        marker = "x" if item_text.strip() in auto_checked_items else " "
        rendered_lines.append(f"{prefix}[{marker}]{spacing}{item_text}")
    return "\n".join(rendered_lines) + "\n"


def finalize_phase3_harness_report(
    request: Phase3HarnessReportRequest,
    *,
    contract_evaluator,
    capture_factory,
    checklist_renderer,
    text_writer,
) -> Phase3HarnessReportResult:
    """Finalize the saved evidence payload for one interactive harness run."""

    payload = dict(request.capture_payload)
    contract = contract_evaluator(payload)
    capture = capture_factory(
        capture_payload=payload,
        contract=contract,
        summary_json_path=request.summary_json_path,
        checklist_results_path=request.checklist_results_path,
        checklist_results_written=bool(request.checklist_results_path),
    )
    text_writer(target_path=request.summary_json_path, content=capture.to_json() + "\n")
    checklist_results = checklist_renderer(
        capture,
        checklist_template_path=request.checklist_template_path,
    )
    text_writer(target_path=request.checklist_results_path, content=checklist_results)
    return Phase3HarnessReportResult(
        capture=capture,
        contract=contract,
        checklist_results=checklist_results,
    )


def _derive_phase3_auto_checked_items(capture: Any) -> set[str]:
    auto_checked: set[str] = set()

    if capture.preview_available:
        auto_checked.add(
            "Confirm the signature properties flow is reachable from the main signing UI."
        )
        auto_checked.add(
            "Confirm the viewer preview renders before any signing action is attempted."
        )
        auto_checked.add(
            "The focused properties panel shows the available appearance controls."
        )

    if not capture.errors:
        auto_checked.add(
            "Confirm the selected PDF can be used without unexpected dependency or backend errors."
        )

    if capture.selection_count > 0:
        auto_checked.add("The user can draw a signature rectangle on the preview.")

    if capture.sign_request_count > 0:
        auto_checked.add("The sign action is available from the properties flow.")

    return auto_checked


def _snapshot_sign_request_appearance(snapshot: dict[str, Any] | None) -> dict[str, Any] | None:
    if snapshot is None:
        return None
    appearance = snapshot.get("signature_appearance")
    if not isinstance(appearance, dict):
        return None
    return appearance


def _snapshot_request_origin(capture: Any) -> str:
    if capture.sign_request_snapshot is None:
        return "not captured"
    if capture.sign_request_count > 0:
        return "submitted request"
    return "current draft"


def _snapshot_layout_template(snapshot: dict[str, Any] | None) -> str | None:
    if snapshot is None:
        return None
    direct_template = snapshot.get("layout_template")
    if isinstance(direct_template, str):
        return direct_template
    appearance = _snapshot_sign_request_appearance(snapshot)
    if appearance is None:
        return None
    layout_template = appearance.get("layout_template")
    return layout_template if isinstance(layout_template, str) else None


def _snapshot_stamp_position(snapshot: dict[str, Any] | None) -> str | None:
    if snapshot is None:
        return None
    direct_position = snapshot.get("stamp_position")
    if isinstance(direct_position, str):
        return direct_position
    appearance = _snapshot_sign_request_appearance(snapshot)
    if appearance is None:
        return None
    stamp_position = appearance.get("stamp_position")
    return stamp_position if isinstance(stamp_position, str) else None


def _snapshot_show_field_names(snapshot: dict[str, Any] | None) -> bool:
    appearance = _snapshot_sign_request_appearance(snapshot)
    if appearance is None:
        return False
    return bool(appearance.get("show_field_names"))


def _snapshot_request_field_count(snapshot: dict[str, Any] | None) -> int:
    appearance = _snapshot_sign_request_appearance(snapshot)
    if appearance is None:
        return 0
    fields = appearance.get("fields")
    if not isinstance(fields, list):
        return 0
    return len(fields)


def _snapshot_preview_edge_distance(snapshot: dict[str, Any] | None, key: str) -> int | None:
    if snapshot is None:
        return None
    edge_distances = snapshot.get("edge_distances_px")
    if not isinstance(edge_distances, dict):
        return None
    value = edge_distances.get(key)
    return int(value) if isinstance(value, int | float) else None


def _snapshot_reservation_text_length(snapshot: dict[str, Any] | None) -> int:
    if snapshot is None:
        return 0
    stamp_text = snapshot.get("stamp_text")
    return len(stamp_text) if isinstance(stamp_text, str) else 0


def _snapshot_reservation_stamp_background(snapshot: dict[str, Any] | None) -> bool:
    if snapshot is None:
        return False
    if "stamp_art_enabled" in snapshot:
        return bool(snapshot.get("stamp_art_enabled"))
    return bool(snapshot.get("stamp_background_present"))


def _snapshot_reservation_stamp_background_text(snapshot: dict[str, Any] | None) -> str:
    return "yes" if _snapshot_reservation_stamp_background(snapshot) else "no"


def _snapshot_layout_scaling(snapshot: dict[str, Any] | None, key: str) -> str | None:
    if snapshot is None:
        return None
    layout_plan = snapshot.get("layout_plan")
    if isinstance(layout_plan, dict):
        scaling = layout_plan.get(f"{key}_scaling")
        return scaling if isinstance(scaling, str) else None
    legacy_layout = snapshot.get(f"{key}_layout")
    if not isinstance(legacy_layout, dict):
        return None
    scaling = legacy_layout.get("inner_content_scaling")
    return scaling if isinstance(scaling, str) else None


def _snapshot_reservation_margin_bottom(snapshot: dict[str, Any] | None) -> int | None:
    if snapshot is None:
        return None
    layout_plan = snapshot.get("layout_plan")
    if isinstance(layout_plan, dict):
        value = layout_plan.get("content_bottom_margin_pt")
        return int(value) if isinstance(value, int | float) else None
    legacy_layout = snapshot.get("content_layout")
    if not isinstance(legacy_layout, dict):
        return None
    margins = legacy_layout.get("margins")
    if not isinstance(margins, dict):
        return None
    value = margins.get("bottom")
    return int(value) if isinstance(value, int | float) else None


def _snapshot_visible_appearance_field_name(snapshot: dict[str, Any] | None) -> str:
    if snapshot is None:
        return "not captured"
    value = snapshot.get("field_name")
    return str(value) if value is not None else "not captured"


def _snapshot_output_signature_value(snapshot: dict[str, Any] | None, key: str) -> str:
    if snapshot is None:
        return "not captured"
    value = snapshot.get(key, "not captured")
    return str(value)


def _snapshot_visible_appearance_annotation_rect(snapshot: dict[str, Any] | None) -> str:
    if snapshot is None:
        return "not captured"
    value = snapshot.get("annotation_rect")
    return str(value) if value is not None else "not captured"


def _snapshot_visible_appearance_bbox(snapshot: dict[str, Any] | None) -> str:
    if snapshot is None:
        return "not captured"
    value = snapshot.get("appearance_bbox")
    return str(value) if value is not None else "not captured"


def _snapshot_visible_appearance_stream_length(snapshot: dict[str, Any] | None) -> int:
    if snapshot is None:
        return 0
    value = snapshot.get("appearance_stream_length")
    return int(value) if isinstance(value, int) else 0


def _snapshot_visible_appearance_has_text(snapshot: dict[str, Any] | None) -> str:
    if snapshot is None:
        return "not captured"
    value = snapshot.get("visible_text_present", snapshot.get("appearance_has_visible_text"))
    if isinstance(value, bool):
        return "yes" if value else "no"
    return "not captured"


def _snapshot_visible_appearance_text_fragments_summary(snapshot: dict[str, Any] | None) -> str:
    if snapshot is None:
        return "not captured"
    fragments = snapshot.get("text_fragments", snapshot.get("appearance_text_fragments"))
    if not isinstance(fragments, list):
        return "not captured"
    if not fragments:
        return "[]"
    preview = ", ".join(repr(fragment) for fragment in fragments[:6])
    if len(fragments) > 6:
        return f"[{preview}, ...]"
    return f"[{preview}]"


def _snapshot_visible_appearance_image_xobjects(snapshot: dict[str, Any] | None) -> str:
    if snapshot is None:
        return "not captured"
    xobjects = snapshot.get("image_xobjects", snapshot.get("appearance_xobjects"))
    if not isinstance(xobjects, list):
        return "not captured"
    if not xobjects:
        return "[]"
    entries: list[str] = []
    for item in xobjects[:6]:
        if not isinstance(item, dict):
            continue
        name = item.get("name")
        subtype = item.get("subtype")
        width = item.get("width")
        height = item.get("height")
        size = f" {width}x{height}" if width is not None and height is not None else ""
        entries.append(f"{name}:{subtype}{size}")
    if len(xobjects) > 6:
        return f"[{', '.join(entries)}, ...]"
    return f"[{', '.join(entries)}]"


def _snapshot_visible_appearance_error(snapshot: dict[str, Any] | None) -> str:
    if snapshot is None:
        return "not captured"
    value = snapshot.get("error")
    return str(value) if value is not None else "none"
