"""Application layer helpers for orchestration and viewer workflows."""

from foliaseal.application.horizontal_signature_reservation import (
    HorizontalSingleLineInkReservation,
    HorizontalSingleLineRenderedReference,
    build_horizontal_single_line_ink_reservation,
    measure_horizontal_single_line_rendered_reference,
)
from foliaseal.application.performance_timing import (
    ViewerPerformanceTracker,
    ViewerTimingSnapshot,
)
from foliaseal.application.signing_draft_workflow import (
    SignaturePlacementContext,
    SigningDraftPreview,
    SigningDraftPreviewField,
    SigningDraftValidationError,
    SigningDraftValidationIssue,
    SigningDraftValidationSeverity,
    SigningDraftWorkflow,
)
from foliaseal.application.signing_preview_renderer import (
    CanonicalSignaturePreviewSnapshot,
    SignatureAppearanceComparison,
    SignatureAppearanceLayerComparison,
    SignatureAppearanceSnapshot,
    SigningPreviewLine,
    SigningPreviewLineKind,
    SigningPreviewParityIssue,
    SigningPreviewParityReport,
    SigningPreviewRenderSnapshot,
    compare_preview_to_request,
    compare_signature_appearance_snapshots,
    render_canonical_signature_preview,
    render_signing_preview,
)
from foliaseal.application.viewer_session import ViewerSession, ViewerZoomLimits
from foliaseal.application.viewer_workflow import ViewerRenderSnapshot, ViewerWorkflow
from foliaseal.application.visible_signature_layout import (
    HorizontalInkMeasurement,
    HorizontalInkMeasurementRequest,
    HorizontalInkMeasurer,
    HorizontalInkReservation,
    ImageMetrics,
    LayoutMargins,
    LayoutRequest,
    LayoutRuleSpec,
    PillowStampImageProbe,
    PyHankoSignatureAppearanceAdapter,
    PyHankoTextMeasurer,
    RectBounds,
    SignatureLayoutPlan,
    StampImageProbe,
    TextMeasurer,
    TextMetrics,
    VisibleSignatureFitIssue,
    VisibleSignatureLayoutEngine,
)

__all__ = [
    "ViewerPerformanceTracker",
    "ViewerRenderSnapshot",
    "ViewerSession",
    "ViewerTimingSnapshot",
    "ViewerWorkflow",
    "ViewerZoomLimits",
    "CanonicalSignaturePreviewSnapshot",
    "HorizontalSingleLineInkReservation",
    "HorizontalSingleLineRenderedReference",
    "HorizontalInkMeasurement",
    "HorizontalInkMeasurementRequest",
    "HorizontalInkMeasurer",
    "HorizontalInkReservation",
    "ImageMetrics",
    "LayoutMargins",
    "LayoutRequest",
    "LayoutRuleSpec",
    "PillowStampImageProbe",
    "PyHankoSignatureAppearanceAdapter",
    "PyHankoTextMeasurer",
    "RectBounds",
    "SignatureAppearanceComparison",
    "SignatureAppearanceLayerComparison",
    "SignatureAppearanceSnapshot",
    "SignatureLayoutPlan",
    "SigningPreviewLine",
    "SigningPreviewLineKind",
    "SigningPreviewParityIssue",
    "SigningPreviewParityReport",
    "SigningPreviewRenderSnapshot",
    "SignaturePlacementContext",
    "SigningDraftPreview",
    "SigningDraftPreviewField",
    "SigningDraftValidationError",
    "SigningDraftValidationIssue",
    "SigningDraftValidationSeverity",
    "SigningDraftWorkflow",
    "StampImageProbe",
    "TextMeasurer",
    "TextMetrics",
    "VisibleSignatureFitIssue",
    "VisibleSignatureLayoutEngine",
    "compare_signature_appearance_snapshots",
    "compare_preview_to_request",
    "build_horizontal_single_line_ink_reservation",
    "measure_horizontal_single_line_rendered_reference",
    "render_canonical_signature_preview",
    "render_signing_preview",
]
